# importation des bibliotheques

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# chargement du dataset

In [2]:
dataset = pd.read_csv("diabetes_dataset (1).csv")
dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
dataset1 = pd.read_csv("dataset_stroke_nouv.csv")
dataset1.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [4]:
dataset1.shape

(5110, 12)

In [5]:
dataset1.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,4856.000000,4390.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.274014,28.930342,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.370994,7.801910,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.407500,23.600000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.990000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.320000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [6]:
dataset1.dtypes

id                     int64
gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [7]:
dataset1.isna().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level    254
bmi                  720
smoking_status         0
stroke                 0
dtype: int64

In [8]:
dataset1['bmi'].isna().sum()

np.int64(720)

In [9]:
dataset1['avg_glucose_level'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
5105    False
5106    False
5107    False
5108    False
5109    False
Name: avg_glucose_level, Length: 5110, dtype: bool

In [10]:
dataset1['bmi'] = dataset1['bmi'].fillna(dataset1['bmi'].mean())
print(dataset1['bmi'])

0       36.600000
1       28.930342
2       32.500000
3       34.400000
4       24.000000
          ...
5105    28.930342
5106    40.000000
5107    28.930342
5108    25.600000
5109    26.200000
Name: bmi, Length: 5110, dtype: float64