In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("EduStats_Students (2) (2).csv")
df.head()

,StudentID,Gender,Age,ParentalEducation,HoursStudyPerWeek,HouseholdIncome,MathScore,ReadingScore,WritingScore,Region,Abs_Jan,Abs_Feb,Abs_Mar,TotalAbsences,InternetAccess,PassFail
0,1,female,20.0,high School,NaN,678932.553965,58.6,46.3,64.4,DAKAR,2.0,1.0,4.0,7.0,yes,1
1,2,Feminin,17.0,master,8.493919,408814.472752,63.2,52.2,53.7,Dakar,2.0,0.0,4.0,6.0,Non,1
2,3,femelle,21.0,high School,7.502857,349577.697114,61.7,56.2,56.8,DAKAR,2.0,4.0,1.0,7.0,No,1
3,4,female,22.0,HS,7.154463,187313.079086,56.1,62.6,45.0,Thies,3.0,1.0,150.0,154.0,yes,1
4,5,F,21.0,MSc,10.986445,245853.740767,53.3,44.3,51.8,thies,4.0,0.0,3.0,7.0,oui,1

### INSPECTION

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2000 non-null   int64
 1   Gender             2000 non-null   object
 2   Age                1910 non-null   float64
 3   ParentalEducation  2000 non-null   object
 4   HoursStudyPerWeek  1867 non-null   float64
 5   HouseholdIncome    1888 non-null   float64
 6   MathScore          2000 non-null   float64
 7   ReadingScore       2000 non-null   float64
 8   WritingScore       2000 non-null   float64
 9   Region             2000 non-null   object
 10  Abs_Jan            2000 non-null   float64
 11  Abs_Feb            2000 non-null   float64
 12  Abs_Mar            2000 non-null   float64
 13  TotalAbsences      2000 non-null   float64
 14  InternetAccess     2000 non-null   object
 15  PassFail           2000 non-null   int64
dtypes: float64(10), int64(2), object(4)
memory usage: 250.1+ KB

In [4]:
df.loc[ : , df.columns != "StudentID"].describe()

,Age,HoursStudyPerWeek,HouseholdIncome,MathScore,ReadingScore,WritingScore,Abs_Jan,Abs_Feb,Abs_Mar,TotalAbsences,PassFail
count,1910.000000,1867.000000,1888.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.00000,2000.00000
mean,20.158115,7.937030,280803.561747,68.083550,61.794050,59.791950,2.03450,2.026000,5.729000,9.78950,0.88150
std,2.456137,3.995969,114198.128017,25.373361,19.424421,15.210044,1.01923,1.154985,19.860987,19.95636,0.32328
min,12.000000,0.004444,-170688.030194,13.900000,-0.200000,-10.000000,0.00000,0.000000,0.000000,0.00000,0.00000
25%,18.000000,4.990817,201551.260919,56.600000,51.500000,50.900000,1.00000,1.000000,2.000000,6.00000,1.00000
50%,20.000000,7.822554,276904.885195,66.850000,60.700000,60.600000,2.00000,2.000000,3.000000,7.00000,1.00000
75%,22.000000,10.748390,355192.999226,76.100000,70.700000,70.000000,3.00000,3.000000,4.000000,9.00000,1.00000
max,28.000000,22.116221,678932.553965,321.500000,214.200000,106.900000,5.00000,6.000000,150.000000,157.00000,1.00000

In [5]:
df.isnull().sum()

StudentID              0
Gender                 0
Age                   90
ParentalEducation      0
HoursStudyPerWeek    133
HouseholdIncome      112
MathScore              0
ReadingScore           0
WritingScore           0
Region                 0
Abs_Jan                0
Abs_Feb                0
Abs_Mar                0
TotalAbsences          0
InternetAccess         0
PassFail               0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

# corrigeons

### genre

In [7]:
df["Gender"].unique()

array(['female', 'Feminin', 'femelle', 'F', 'FEMALE', 'male ', 'Masculin',
       'Male'], dtype=object)

In [8]:
for i in range(len(df)):
    if str(df.loc[i, "Gender"]).strip().upper().startswith("F"):
        df.loc[i, "Gender"] = "F"
    else:
        df.loc[i, "Gender"] = "M"

In [9]:
df["Gender"].unique()

array(['F', 'M'], dtype=object)

In [10]:
df["Gender"].replace(to_replace=r'^\s*F.*', value='F', regex=True, inplace=True)

C:\Users\samba\AppData\Local\Temp\ipykernel_23128\3601562667.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].replace(to_replace=r'^\s*F.*', value='F', regex=True, inplace=True)

In [11]:
df["Gender"].replace(to_replace=r'^\s*M.*', value='M', regex=True, inplace=True)

C:\Users\samba\AppData\Local\Temp\ipykernel_23128\1612451181.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].replace(to_replace=r'^\s*M.*', value='M', regex=True, inplace=True)

In [12]:
df["Gender"].unique()

array(['F', 'M'], dtype=object)

In [13]:
df.tail(15)

,StudentID,Gender,Age,ParentalEducation,HoursStudyPerWeek,HouseholdIncome,MathScore,ReadingScore,WritingScore,Region,Abs_Jan,Abs_Feb,Abs_Mar,TotalAbsences,InternetAccess,PassFail
1985,1986,M,22.0,Bachelor,13.239461,553921.446820,83.1,60.4,67.2,Dakar,2.0,3.0,1.0,6.0,Y,1
1986,1987,M,20.0,MSc,7.702619,NaN,50.7,60.7,63.2,Thiès,1.0,3.0,2.0,6.0,Yes,1
1987,1988,F,21.0,master,7.261794,69214.045655,73.1,63.5,62.0,Thiès,3.0,3.0,2.0,8.0,Non,1
1988,1989,F,19.0,Bachelor,10.369318,270579.309378,68.7,51.8,49.4,DAKAR,1.0,3.0,3.0,7.0,OUI,1
1989,1990,F,20.0,Bachelor,8.397255,117790.116141,69.4,58.0,56.8,saint louis,1.0,2.0,2.0,5.0,No,1
1990,1991,F,19.0,High school,6.438365,199812.767390,70.0,66.9,59.9,dakar,2.0,0.0,3.0,5.0,OUI,1
1991,1992,F,18.0,Bachelor,10.064576,389872.333657,72.8,63.7,68.9,DAKAR,2.0,3.0,3.0,8.0,OUI,1
1992,1993,F,20.0,Licence,5.389887,479297.027672,74.7,71.1,70.8,DAKAR,0.0,2.0,1.0,3.0,OUI,1
1993,1994,M,16.0,Licence,5.555291,324167.347046,74.4,73.8,80.9,Saint-Louis,3.0,0.0,3.0,6.0,OUI,1
1994,1995,F,19.0,HS,5.888024,194942.928210,48.0,48.2,50.0,DAKAR,3.0,1.0,2.0,6.0,No,0
1995,1996,M,NaN,master,13.412277,62593.810011,61.2,59.0,61.4,Saint-Louis,3.0,2.0,5.0,10.0,yes,1
1996,1997,M,19.0,Master,NaN,303142.217902,52.0,47.8,44.9,Dakar,2.0,2.0,2.0,6.0,Y,1
1997,1998,M,19.0,MSc,9.582395,308554.471266,61.2,45.0,50.5,thies,0.0,2.0,2.0,4.0,OUI,1
1998,1999,F,20.0,Bachelor,NaN,376674.817706,54.0,50.9,60.9,thies,2.0,3.0,2.0,7.0,Y,1
1999,2000,M,21.0,Bachelor,1.276518,214981.427817,67.6,67.6,66.5,dakar,1.0,1.0,3.0,5.0,yes,1

In [14]:
#unformisons la colonne "Gender" 
df["Gender"] = df["Gender"].apply(lambda x: "F" if str(x).strip().upper().startswith("F") else "M")

In [15]:
df.head(10)

,StudentID,Gender,Age,ParentalEducation,HoursStudyPerWeek,HouseholdIncome,MathScore,ReadingScore,WritingScore,Region,Abs_Jan,Abs_Feb,Abs_Mar,TotalAbsences,InternetAccess,PassFail
0,1,F,20.0,high School,NaN,678932.553965,58.6,46.3,64.4,DAKAR,2.0,1.0,4.0,7.0,yes,1
1,2,F,17.0,master,8.493919,408814.472752,63.2,52.2,53.7,Dakar,2.0,0.0,4.0,6.0,Non,1
2,3,F,21.0,high School,7.502857,349577.697114,61.7,56.2,56.8,DAKAR,2.0,4.0,1.0,7.0,No,1
3,4,F,22.0,HS,7.154463,187313.079086,56.1,62.6,45.0,Thies,3.0,1.0,150.0,154.0,yes,1
4,5,F,21.0,MSc,10.986445,245853.740767,53.3,44.3,51.8,thies,4.0,0.0,3.0,7.0,oui,1
5,6,F,23.0,Licence,9.302311,284303.928753,52.0,47.1,45.9,saint louis,2.0,4.0,4.0,10.0,oui,1
6,7,F,22.0,high School,17.103302,335139.461230,73.4,56.0,59.6,thies,3.0,2.0,4.0,9.0,Yes,1
7,8,F,21.0,master,4.591101,74347.734712,79.7,66.6,69.8,Saint-Louis,3.0,2.0,1.0,6.0,yes,1
8,9,F,20.0,High school,10.072407,67720.517730,74.8,64.4,62.2,Thiès,2.0,2.0,3.0,7.0,Y,1
9,10,M,16.0,MSc,5.883196,223574.113327,78.6,61.9,75.1,Dakar,3.0,3.0,3.0,9.0,No,1

# ParentalEducation

In [16]:
df["ParentalEducation"].unique()

array(['high School', 'master ', 'HS', 'MSc', 'Licence', 'High school',
       'Master', 'Bachelor'], dtype=object)

In [17]:
for i in range(len(df)):
    pe = str(df.loc[i, "ParentalEducation"]).strip().upper()
    if "H" in pe and "S" in pe:
        df.loc[i, "ParentalEducation"] = "High School"
    elif str(df.loc[i, "ParentalEducation"]).strip().upper().startswith("B") or str(df.loc[i, "ParentalEducation"]).strip().upper().startswith("L"):
        df.loc[i, "ParentalEducation"] = "Bachelor"
    elif "M" in pe and "S" in pe:
        df.loc[i, "ParentalEducation"] = "Master"
    else:
        df.loc[i, "ParentalEducation"] = np.nan

In [18]:
df["ParentalEducation"].unique()

array(['High School', 'Master', 'Bachelor'], dtype=object)

# region

In [19]:
# #les 1ere lettres de la colonne Region en majuscule
# df["Region"] = df["Region"].apply(lambda x: str(x).strip().capitalize())
# df["Region"]

In [20]:
for i in range(len(df)):
    df.loc[i, "Region"] = str(df.loc[i, "Region"]).strip().capitalize()

In [21]:
df["Region"].head(10)

0          Dakar
1          Dakar
2          Dakar
3          Thies
4          Thies
5    Saint louis
6          Thies
7    Saint-louis
8          Thiès
9          Dakar
Name: Region, dtype: object

In [22]:
df["Region"].unique()

array(['Dakar', 'Thies', 'Saint louis', 'Saint-louis', 'Thiès'],
      dtype=object)

# InternetAccess

In [23]:
df["InternetAccess"].unique()

array(['yes', 'Non', 'No', 'oui', 'Yes', 'Y', 'OUI', '1', '0'],
      dtype=object)

In [24]:
dico = {
        "yes": 1, 
        "oui": 1, 
        "Yes": 1, 
        "Y": 1, 
        "OUI": 1, 
        "1": 1,

        "Non": 0, 
        "No": 0, 
        "0": 0}
df["InternetAccess"] = df["InternetAccess"].replace(dico)
df["InternetAccess"]

C:\Users\samba\AppData\Local\Temp\ipykernel_23128\2845503242.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["InternetAccess"] = df["InternetAccess"].replace(dico)

0       1
1       0
2       0
3       1
4       1
       ..
1995    1
1996    1
1997    1
1998    1
1999    1
Name: InternetAccess, Length: 2000, dtype: int64

In [25]:
df["InternetAccess"].unique()

array([1, 0])

In [26]:
#sauvegarde
df.to_csv("Students_cleaned.csv", index=False)